# Generated by Django 5.0.7 on 2024-08-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewer',
            unique_together={('user', 'channel')},
        ),
    ]
